# Generated by Django 5.1.3 on 2024-11-09 20:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="community",
            name="description",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="community",
            name="name",
            field=models.CharField(max_length=100),
        ),
    ]
