# Generated by Django 5.1.3 on 2024-11-09 22:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_community_description_alter_community_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("city", models.CharField(max_length=200)),
                ("country", models.CharField(max_length=200)),
                ("postal_code", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("latitudeDelta", models.FloatField()),
                ("longitudeDelta", models.FloatField()),
            ],
        ),
        migrations.AlterField(
            model_name="community",
            name="name",
            field=models.CharField(max_length=200),
        ),
    ]
